<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for your orderYour order has _f1f997</name>
   <tag></tag>
   <elementGuidId>c5ee6522-376f-4abe-82cc-9cbd4f8a6732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_complete_container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkout_complete_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc3376b9-5af3-47a5-8c55-f0b98c68bc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout_complete_container</value>
      <webElementGuid>9ee81df7-33a3-46f2-80f5-a21a837f6105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout_complete_container</value>
      <webElementGuid>af77b062-42b4-4136-b70e-c2d508853c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home</value>
      <webElementGuid>d915a762-6584-45ee-804a-de0e5c9dcbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_complete_container&quot;)</value>
      <webElementGuid>357f7294-f036-4f57-8ca0-269cdaf039d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='checkout_complete_container']</value>
      <webElementGuid>22cd93cf-4973-4b45-bf10-cdbcf4c26272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contents_wrapper']/div[2]</value>
      <webElementGuid>c985ae31-7d93-4251-8e0c-4df4f8af11df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout: Complete!'])[1]/following::div[1]</value>
      <webElementGuid>72d6edc6-1788-4a65-89ae-f3360a202706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swag Labs'])[2]/following::div[3]</value>
      <webElementGuid>72f471d6-23e1-400f-af87-2e00b5f182d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>431569b6-cc8c-474e-9c78-9c1b3e305185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkout_complete_container' and (text() = 'Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home' or . = 'Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home')]</value>
      <webElementGuid>fa39c581-5b69-4a68-bd23-3013dbb88c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
